apiVersion: v1
kind: Service
metadata:
  name: matmul
spec:
  selector:
    app: matmul
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matmul
spec:
  selector:
    matchLabels:
      app: matmul
  replicas: 2
  template:
    metadata:
      labels:
        app: matmul
    spec:
      containers:
      - name: matmul
        image: nusjzx/float-operation:latest # Change image name according to the docker image created
        ports:
        - containerPort: 8080
